---
- name: install latest pip from apt
  apt: pkg=python-pip state=installed
  tags: pip

- name: install pip from pypi
  pip: name=pip version=1.5.6
  tags: pip

- name: install virtualenv
  pip: name=virtualenv version=1.11.6
  tags: pip

- name: install build-essential
  apt: pkg=build-essential state=installed

- name: install python-dev
  apt: pkg=python-dev state=installed
