language: python

python:
  - '2.7'
  - '3.3'

env:
  - DJANGO="" DJANGO_SETTINGS_MODULE="richard.config.settings" DJANGO_CONFIGURATION="Testing"
#  - DJANGO="https://github.com/django/django/archive/1.7b1.zip"

install:
  - 'pip install -e .[dev]'
#  - 'if ( test -n "$DJANGO" ); then pip install $DJANGO; fi'

script:
  - 'py.test ./tests'

notifications:
  irc:
    channels:
      - "irc.freenode.org#richard"
    on_success: change
    on_failure: always
